= Testnet Demo

IMPORTANT:
The latest sdk has not been released, hence use this sdk version and link locally:
https://github.com/comit-network/comit-js-sdk/tree/inmeory-btc-wallet

== Intro

Synced testnet nodes are a requirement for running the COMIT Node Daemon (cnd) against testnet. 
In order to make your life easier we provide fully synced testnet nodes for your cnd here:

Note that our testnet nodes might not always be running, but are just started before workshops/events.
If you have any questions please contact us through the [COMIT community chat on gitter](https://gitter.im/comit-network/community).

This guide assumes that you run both the taker and the maker on the same machine (for the example's sake).
In a more real world scenario maker and taker would of course be separate people on separate machines.

== Setup

=== Run cnd taker

Create a config file for the taker in `taker/config.toml` with the following content:

[source,toml]
.taker.toml
----
include::taker/config.toml_example[]
----

Create a seed file for the taker in `taker/seed.pem`:

[source,pem]
.seed.pem
----
include::taker/seed.pem[]
----

We assume that cnd is in your path. For how to do so have a look at: https://github.com/comit-network/comit-rs/readme.md

Startup command:
[source,bash]
----
cnd --config config.toml
----

=== Run cnd maker
Create a config file for the maker in `maker/config.toml` with the following content:

[source,toml]
.taker.toml
----
include::maker/config.toml_example[]
----


Create a seed file for the maker in `maker/seed.pem`:

[source,pem]
.seed.pem
----
include::maker/seed.pem[]
----

We assume that cnd is in your path. For how to do so have a look at: https://github.com/comit-network/comit-rs/readme.md
Startup command:

[source,bash]
----
cnd --config config.toml
----



=== Key/account generation and funding for both wallets

Keep in mind when running both maker and taker on the same machine you have to create a Bitcoin and Ethereum account for both maker and taker, thus you have to create and fund **two Bitcoin** and **two Ethereum** accounts.

==== Bitcoin

1. Generate HD key (master-key) with [Wagyu](https://github.com/ArgusHQ/wagyu): +
`wagyu bitcoin hd --network testnet --derivation "m"`

2. Copy the `Extended Private Key` generated by Wagyu into the `env` file for `maker` and `taker`.

3. Once the maker (or taker) is started, it will print you some addresses which you will need to fund using an online faucet e.g.
https://testnet-faucet.mempool.co/

==== Ethereum

1. Generate an Ethereum account with [Wagyu](https://github.com/ArgusHQ/wagyu) +
`wagyu ethereum hd`
2. Copy the `Private Key` (NOT the extended private key) to the env file for maker and taker.
3. Fund the account through an https://faucet.ropsten.be/[Ethereum ropsten coin faucet]


== Run the example

. Both maker and taker cnd are running,
. `env` files were properly initialized with the bitcoin HD keys and Ethereum private keys
. Bitcoin addresses and Ethereum accounts were properly funded.
. Start the maker: +
`yarn run maker`
. Start the taker: +
. The wallets will sync at the beginning which takes a while depending on your internet connection and computer.
The swap should happen completely automated (note: this may take a while given testnets are not reliable).

== Appendix

=== CoBloX Testnet Node Status

==== Ethereum
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' -H "Content-type:application/json" bobtimus.coblox.tech:8545 | jq .
```

Returns the syncing status.

==== Bitcoin
```
curl bobtimus.coblox.tech:18332/rest/chaininfo.json |  jq .
```

Returns basic chain status information.
